/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedOfertasRouteImport } from './routes/_authenticated/ofertas'
import { Route as AuthenticatedAdminFilaOfertasRouteImport } from './routes/_authenticated/admin/fila-ofertas'
import { Route as AuthenticatedAdminMercadosRouteImport } from './routes/_authenticated/admin/mercados'
import { Route as AuthenticatedAdminNotasRouteImport } from './routes/_authenticated/admin/notas'
import { Route as AuthenticatedAdminPrecosRouteImport } from './routes/_authenticated/admin/precos'
import { Route as AuthenticatedAdminProdutosRouteImport } from './routes/_authenticated/admin/produtos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOfertasRoute = AuthenticatedOfertasRouteImport.update({
  id: '/ofertas',
  path: '/ofertas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminFilaOfertasRoute =
  AuthenticatedAdminFilaOfertasRouteImport.update({
    id: '/admin/fila-ofertas',
    path: '/admin/fila-ofertas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminMercadosRoute =
  AuthenticatedAdminMercadosRouteImport.update({
    id: '/admin/mercados',
    path: '/admin/mercados',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminNotasRoute = AuthenticatedAdminNotasRouteImport.update({
  id: '/admin/notas',
  path: '/admin/notas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminPrecosRoute =
  AuthenticatedAdminPrecosRouteImport.update({
    id: '/admin/precos',
    path: '/admin/precos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminProdutosRoute =
  AuthenticatedAdminProdutosRouteImport.update({
    id: '/admin/produtos',
    path: '/admin/produtos',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/ofertas': typeof AuthenticatedOfertasRoute
  '/admin/fila-ofertas': typeof AuthenticatedAdminFilaOfertasRoute
  '/admin/mercados': typeof AuthenticatedAdminMercadosRoute
  '/admin/notas': typeof AuthenticatedAdminNotasRoute
  '/admin/precos': typeof AuthenticatedAdminPrecosRoute
  '/admin/produtos': typeof AuthenticatedAdminProdutosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/entrar': typeof EntrarRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/ofertas': typeof AuthenticatedOfertasRoute
  '/admin/fila-ofertas': typeof AuthenticatedAdminFilaOfertasRoute
  '/admin/mercados': typeof AuthenticatedAdminMercadosRoute
  '/admin/notas': typeof AuthenticatedAdminNotasRoute
  '/admin/precos': typeof AuthenticatedAdminPrecosRoute
  '/admin/produtos': typeof AuthenticatedAdminProdutosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/entrar': typeof EntrarRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/ofertas': typeof AuthenticatedOfertasRoute
  '/_authenticated/admin/fila-ofertas': typeof AuthenticatedAdminFilaOfertasRoute
  '/_authenticated/admin/mercados': typeof AuthenticatedAdminMercadosRoute
  '/_authenticated/admin/notas': typeof AuthenticatedAdminNotasRoute
  '/_authenticated/admin/precos': typeof AuthenticatedAdminPrecosRoute
  '/_authenticated/admin/produtos': typeof AuthenticatedAdminProdutosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/entrar'
    | '/historico'
    | '/ofertas'
    | '/admin/fila-ofertas'
    | '/admin/mercados'
    | '/admin/notas'
    | '/admin/precos'
    | '/admin/produtos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/entrar'
    | '/historico'
    | '/ofertas'
    | '/admin/fila-ofertas'
    | '/admin/mercados'
    | '/admin/notas'
    | '/admin/precos'
    | '/admin/produtos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/entrar'
    | '/_authenticated/historico'
    | '/_authenticated/ofertas'
    | '/_authenticated/admin/fila-ofertas'
    | '/_authenticated/admin/mercados'
    | '/_authenticated/admin/notas'
    | '/_authenticated/admin/precos'
    | '/_authenticated/admin/produtos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  EntrarRoute: typeof EntrarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ofertas': {
      id: '/_authenticated/ofertas'
      path: '/ofertas'
      fullPath: '/ofertas'
      preLoaderRoute: typeof AuthenticatedOfertasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/fila-ofertas': {
      id: '/_authenticated/admin/fila-ofertas'
      path: '/admin/fila-ofertas'
      fullPath: '/admin/fila-ofertas'
      preLoaderRoute: typeof AuthenticatedAdminFilaOfertasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/mercados': {
      id: '/_authenticated/admin/mercados'
      path: '/admin/mercados'
      fullPath: '/admin/mercados'
      preLoaderRoute: typeof AuthenticatedAdminMercadosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/notas': {
      id: '/_authenticated/admin/notas'
      path: '/admin/notas'
      fullPath: '/admin/notas'
      preLoaderRoute: typeof AuthenticatedAdminNotasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/precos': {
      id: '/_authenticated/admin/precos'
      path: '/admin/precos'
      fullPath: '/admin/precos'
      preLoaderRoute: typeof AuthenticatedAdminPrecosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/produtos': {
      id: '/_authenticated/admin/produtos'
      path: '/admin/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AuthenticatedAdminProdutosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedOfertasRoute: typeof AuthenticatedOfertasRoute
  AuthenticatedAdminFilaOfertasRoute: typeof AuthenticatedAdminFilaOfertasRoute
  AuthenticatedAdminMercadosRoute: typeof AuthenticatedAdminMercadosRoute
  AuthenticatedAdminNotasRoute: typeof AuthenticatedAdminNotasRoute
  AuthenticatedAdminPrecosRoute: typeof AuthenticatedAdminPrecosRoute
  AuthenticatedAdminProdutosRoute: typeof AuthenticatedAdminProdutosRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedOfertasRoute: AuthenticatedOfertasRoute,
  AuthenticatedAdminFilaOfertasRoute: AuthenticatedAdminFilaOfertasRoute,
  AuthenticatedAdminMercadosRoute: AuthenticatedAdminMercadosRoute,
  AuthenticatedAdminNotasRoute: AuthenticatedAdminNotasRoute,
  AuthenticatedAdminPrecosRoute: AuthenticatedAdminPrecosRoute,
  AuthenticatedAdminProdutosRoute: AuthenticatedAdminProdutosRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  EntrarRoute: EntrarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
